services:
  - type: web
    name: cs16-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
